# Generated by Django 5.2.6 on 2025-09-10 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField()),
                ('current_location_lng', models.FloatField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField()),
                ('pickup_location_lng', models.FloatField()),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField()),
                ('dropoff_location_lng', models.FloatField()),
                ('current_cycle_used', models.FloatField(help_text='Current cycle hours used (0-70)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Break'), ('meal', 'Meal Break'), ('sleeper', 'Sleeper Break')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('estimated_arrival', models.DateTimeField()),
                ('estimated_departure', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_from_previous', models.FloatField(default=0)),
                ('cumulative_distance', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.trip')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
