# Generated by Django 5.2.6 on 2025-09-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('odometer_start', models.IntegerField(blank=True, null=True)),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('hours', models.FloatField()),
                ('remarks', models.TextField(blank=True)),
                ('cycle_hours_used', models.FloatField(default=0)),
                ('daily_driving_hours', models.FloatField(default=0)),
                ('daily_duty_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='routes.trip')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('11_hour_driving', '11-Hour Driving Limit'), ('14_hour_duty', '14-Hour Duty Limit'), ('70_hour_cycle', '70-Hour/8-Day Cycle'), ('10_hour_break', '10-Hour Break Requirement'), ('30_minute_break', '30-Minute Break Requirement')], max_length=30)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('violation_time', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.driver')),
                ('eld_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.eldlog')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='routes.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_id', models.CharField(blank=True, max_length=50)),
                ('odometer_start', models.IntegerField(blank=True, null=True)),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('total_miles', models.IntegerField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_hours', models.FloatField(default=0)),
                ('cycle_hours_remaining', models.FloatField(default=70)),
                ('next_drive_time_available', models.DateTimeField(blank=True, null=True)),
                ('log_sheet_file', models.FileField(blank=True, null=True, upload_to='log_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='routes.trip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trip', 'driver', 'date')},
            },
        ),
    ]
